import 'package:Burn/data_models.dart/beginner_exercises.dart';

class WeekOneLowerBodyBeginnerGym {
  static BeginnersExercisesName names = BeginnersExercisesName();
  static BeginnersExercisesAudios audio = BeginnersExercisesAudios();
  static BeginnersExerciseGifs gif = BeginnersExerciseGifs();
  static BeginnersExercisesAudios audioT = BeginnersExercisesAudios();
  static BeginnersExercisesInstructions inst = BeginnersExercisesInstructions();
  List<Map> exerciseData = [
    {
      'equipments': [
        {
          'equipmetnName': 'Kettlebell',
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'equipmentImageUrl':
              'https://www.pngmart.com/files/7/Kettlebell-PNG-Free-Download.png',
        },
        {
          'equipmetnName': 'Medicine Ball',
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'equipmentImageUrl':
              'https://firebasestorage.googleapis.com/v0/b/burn-2fa49.appspot.com/o/pngfind.com-pokemon-ball-png-2903453.png?alt=media&token=28eecb96-ed6f-45ed-86ee-f02649ec1e4c',
        },
        {
          'equipmetnName': 'Dumbbells',
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'equipmentImageUrl':
              'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZZtu__nsnNxlkl48omMAzqW2Q5BdNnW63PA&usqp=CAU',
        },
        {
          'equipmetnName': 'Loop Resistance Band',
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'equipmentImageUrl':
              'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZZtu__nsnNxlkl48omMAzqW2Q5BdNnW63PA&usqp=CAU',
        },
        {
          'equipmetnName': 'Loop Resistance Band',
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'equipmentImageUrl':
              'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZZtu__nsnNxlkl48omMAzqW2Q5BdNnW63PA&usqp=CAU',
        },
      ]
    },
    {
      'exercises': [
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'exerciseName': names.kneePullDowns,
          'circuit': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'index': 0,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audio.KNEEPULLDOWNSTIP,
          'instructions': inst.kneePullDowns,
          'gifUrl': gif.kneePullDowns,
          'audioLink': audio.KNEEPULLDOWNS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'workoutType': 1,
          'exerciseName': names.uprightRow,
          'circuit': 1,
          'index': 1,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.UPRIGHTROWTIP,
          'instructions': inst.uprightRow,
          'gifUrl': gif.uprightRow,
          'audioLink': audio.UPRIGHTROW,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.donkeyKick,
          'circuit': 1,
          'index': 2,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.DONKEYKICKTIP,
          'instructions': inst.donkeyKick,
          'gifUrl': gif.donkeyKick,
          'audioLink': audio.DONKEYKICKS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'exerciseName': names.halfBike,
          'circuit': 2,
          'index': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFBIKETIP,
          'instructions': inst.halfBike,
          'gifUrl': gif.halfBike,
          'audioLink': audio.HALFBIKE,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'exerciseName': names.tricepDips,
          'circuit': 2,
          'index': 4,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TRICEPDIPTIP,
          'instructions': inst.tricepDips,
          'gifUrl': gif.tricepDips,
          'audioLink': audio.TRICEPDIPS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'exerciseName': names.sumoSquate,
          'circuit': 2,
          'index': 5,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'audioTip': audioT.SUMOSQUATTIP,
          'instructions': inst.sumoSquate,
          'gifUrl': gif.sumoSquate,
          'audioLink': audio.SUMOSQUATS,
        },
        {
          'level': 1,
          'week': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'place': 2,
          'workoutType': 1,
          'exerciseName': names.alternatingLung,
          'circuit': 3,
          'index': 6,
          // 03414687643
          'exerciseTime': 40,

          'restTime': 15,
          'audioTip': audioT.ALTLUNGETIP,
          'instructions': inst.alternatingLung,
          'gifUrl': gif.alternatingLung,
          'audioLink': audio.ALTERNATINGLUNGES,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'workoutType': 1,
          'exerciseName': names.toeTaps,
          'circuit': 3,
          'index': 7,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TOETAPSTIP,
          'instructions': inst.toeTaps,
          'gifUrl': gif.toeTaps,
          'audioLink': audio.TOETAPS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 1,
          'exerciseName': names.plank,
          'circuit': 3,
          'index': 8,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.PLANKTIP,
          'instructions': inst.plank,
          'gifUrl': gif.plank,
          'audioLink': audio.PLANK,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.buttKicks,
          'circuit': 1,
          'index': 9,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BUTTKICKTIP,
          'instructions': inst.buttKicks,
          'gifUrl': gif.buttKicks,
          'audioLink': audio.BUTTKICKS
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squat,
          'circuit': 1,
          'index': 10,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATTIP,
          'instructions': inst.squat,
          'gifUrl': gif.squat,
          'audioLink': audio.SQUAT,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gluteBridges,
          'circuit': 1,
          'index': 11,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GLUTEBRIDGETIP,
          'instructions': inst.gluteBridges,
          'gifUrl': gif.gluteBridges,
          'audioLink': audio.GLUTEBRIDGES
        },
        {
          'level': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'exerciseName': names.halfXJumps,
          'circuit': 2,
          'index': 12,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFXJUMPTIP,
          'instructions': inst.halfXJumps,
          'gifUrl': gif.halfXJumps,
          'audioLink': audio.HALFXJUMP,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.staticLunge,
          'circuit': 2,
          'index': 13,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STATICLUNGETIP,
          'instructions': inst.staticLunge,
          'gifUrl': gif.staticLunge,
          'audioLink': audio.STATICLUNGES,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.goodMorning,
          'circuit': 2,
          'index': 14,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GOODMORNINGTIP,

          'instructions': inst.goodMorning,
          'gifUrl': gif.goodMorning,
          'audioLink': audio.GOODMORNING,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.stepUps,
          'circuit': 3,
          'index': 15,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STEPUPTIP,
          'instructions': inst.stepUps,
          'gifUrl': gif.stepUps,
          'audioLink': audio.STEPUPS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'workoutType': 2,
          'exerciseName': names.innerThighLegLift,
          'circuit': 3,
          'index': 16,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.INNERTHIGHLEGLIFTTIP,
          'instructions': inst.innerThighLegLift,
          'gifUrl': gif.innerThighLegLift,
          'audioLink': audio.INNERTHIGHLEGLIFT,
        },
        {
          'level': 1,
          'week': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'place': 2,
          'workoutType': 2,
          'exerciseName': names.calm,
          'circuit': 3,
          'index': 17,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.CLAMTIP,
          'instructions': inst.calm,
          'gifUrl': gif.calm,
          'audioLink': audio.CLAM,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.slowMountainClimbers,
          'circuit': 1,
          'index': 18,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SLOWMOUNTAINCLIMBERS,
          'instructions': inst.slowMountainClimbers,
          'gifUrl': gif.slowMountainClimbers,
          'audioLink': audio.SLOWMOUNTAINCLIMBERS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'workoutType': 3,
          'exerciseName': names.alternatingBicepsCurlsName,
          'circuit': 1,
          'index': 19,
          // 03414687643
          'exerciseTime': 40,

          'restTime': 15,
          'audioTip': audioT.ALTERNATINGBICEPCURLS,
          'instructions': inst.alternatingBicepCurls,
          'gifUrl': gif.slowMountainClimbers,
          'audioLink': audio.ALTERNATINGBICEPCURLS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'exerciseName': names.tricepDips,
          'circuit': 1,
          'index': 20,
          // 03414687643
          'exerciseTime': 40,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'restTime': 15,
          'audioTip': audioT.TRICEPDIPTIP,
          'instructions': inst.tricepDips,
          'gifUrl': gif.tricepDips,
          'audioLink': audio.TRICEPDIPS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'exerciseName': names.bandPullAparts,
          'circuit': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'index': 21,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BANDPULLAPARTSTIP,
          'instructions': inst.bandPullAparts,
          'gifUrl': gif.bandPullAparts,
          'audioLink': audio.BANDPULLAPARTS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'exerciseName': names.halfSidePlank,
          'circuit': 2,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'index': 22,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFSIDEPLANKTIP,
          'instructions': inst.halfSidePlank,
          'gifUrl': gif.halfSidePlank,
          'audioLink': audio.HALFSIDEPLANK,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'workoutType': 3,
          'exerciseName': names.seatedRow,
          'circuit': 2,
          'index': 23,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SEATEDROWTIP,
          'instructions': inst.seatedRow,
          'gifUrl': gif.seatedRow,
          'audioLink': audio.SEATEDROW,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.starJumps,
          'circuit': 3,
          'index': 24,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STARJUMPSTIP,
          'instructions': inst.starJumps,
          'gifUrl': gif.starJumps,
          'audioLink': audio.STARJUMPS,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.superMan,
          'circuit': 3,
          'index': 25,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUPERMANTIP,
          'instructions': inst.superMan,
          'gifUrl': gif.superMan,
          'audioLink': audio.SUPERMAN,
        },
        {
          'level': 1,
          'week': 1,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfPressUps,
          'circuit': 3,
          'index': 26,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFPRESSUPTIP,
          'instructions': inst.halfPressUps,
          'gifUrl': gif.halfPressUps,
          'audioLink': audio.HALFPRESSUPS
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.buttKicks,
          'circuit': 1,
          'index': 27,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BUTTKICKTIP,
          'instructions': inst.buttKicks,
          'gifUrl': gif.buttKicks,
          'audioLink': audio.BUTTKICKS
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squat,
          'circuit': 1,
          'index': 28,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATTIP,
          'instructions': inst.squat,
          'gifUrl': gif.squat,
          'audioLink': audio.SQUAT,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': 'Aquaman',
          'circuit': 1,
          'index': 29,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.AQUAMANTIP,
          'instructions': 'aquamen',
          'gifUrl': 'aquamen',
          'audioLink': audio.AQUAMAN,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfRussianTwists,
          'circuit': 2,
          'index': 30,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFRUSSIANTWISTS,
          'instructions': inst.halfRussianTwists,
          'gifUrl': gif.halfRussianTwists,
          'audioLink': audio.HALFRUSSIANTWISTS,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.lateralJumps,
          'circuit': 2,
          'index': 31,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LATERALJUMPSTIP,
          'instructions': inst.lateralJumps,
          'gifUrl': gif.lateralJumps,
          'audioLink': audio.LATERALJUMPS
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfPressUps,
          'circuit': 2,
          'index': 32,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFPRESSUPTIP,
          'instructions': inst.halfPressUps,
          'gifUrl': gif.halfPressUps,
          'audioLink': audio.HALFPRESSUPS,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.stepKneeDrive,
          'circuit': 3,
          'index': 33,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STEPKNEEDRIVETIP,
          'instructions': inst.stepKneeDrive,
          'gifUrl': gif.stepKneeDrive,
          'audioLink': audio.STEPKNEEDRIVE,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.obliqueCrunch,
          'circuit': 3,
          'index': 34,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.OBLIQUECRUNCHTIP,
          'instructions': inst.obliqueCrunch,
          'gifUrl': gif.obliqueCrunch,
          'audioLink': audio.OBLIQUECRUNCH,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.toeTaps,
          'circuit': 1,
          'index': 35,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TOETAPSTIP,
          'instructions': inst.toeTaps,
          'gifUrl': gif.toeTaps,
          'audioLink': audio.TOETAPS,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squatAndLegLift,
          'circuit': 1,
          'index': 36,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATANDLEGLIFTTIP,
          'instructions': inst.squatAndLegLift,
          'gifUrl': gif.squatAndLegLift,
          'audioLink': audio.SQUATANDLEGLIFT,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.elevatedGluteBridgesBench,
          'circuit': 1,
          'index': 37,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ELEVATEDGLUTEBRIDGETIP,
          'instructions': inst.elevatedGluteBridgesBench,
          'gifUrl': gif.elevatedGluteBridgesBench,
          'audioLink': audio.ELEVATEDGLUTEBRIDGE,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.popSquats,
          'circuit': 2,
          'index': 38,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.POPSQUATTIP,
          'instructions': inst.popSquats,
          'gifUrl': gif.popSquats,
          'audioLink': audio.POPSQUATS,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.standingGluteKickback,
          'circuit': 2,
          'index': 39,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STANDINGGLUTEKICKBACKTIP,
          'instructions': inst.standingGluteKickback,
          'gifUrl': gif.standingGluteKickback,
          'audioLink': audio.STANDINGGLUTEKICKBACK,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingReverseLung,
          'circuit': 2,
          'index': 40,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGREVERSELUNGES,
          'instructions': inst.alternatingReverseLung,
          'gifUrl': gif.alternatingReverseLung,
          'audioLink': audio.ALTERNATINGREVERSELUNGES,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfBurpees,
          'circuit': 3,
          'index': 41,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFBURPEETIP,
          'instructions': inst.halfBurpees,
          'gifUrl': gif.halfBurpees,
          'audioLink': audio.HALFBURPEES,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.fireHydrant,
          'circuit': 3,
          'index': 42,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.FIREHYDRANTTIP,
          'instructions': inst.fireHydrant,
          'gifUrl': gif.fireHydrant,
          'audioLink': audio.FIREHYDRANT,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.singleLegLateralLunge,
          'circuit': 3,
          'index': 43,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SINGLELEGLATERALLUNGETIP,
          'instructions': inst.singleLegLateralLunge,
          'gifUrl': gif.singleLegLateralLunge,
          'audioLink': audio.SINGLELEGLATERALLUNGE,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.shoulderRotations,
          'circuit': 1,
          'index': 44,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SHOULDERROTATIONSTIP,
          'instructions': inst.shoulderRotations,
          'gifUrl': gif.shoulderRotations,
          'audioLink': audio.SHOULDERROTATIONS,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfSitUp,
          'circuit': 1,
          'index': 45,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFSITUPTIP,
          'instructions': inst.halfSitUp,
          'gifUrl': gif.halfSitUp,
          'audioLink': audio.HALFSITUP,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bridgeHold,
          'circuit': 1,
          'index': 46,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BRIDGEHOLDTIP,
          'instructions': inst.bridgeHold,
          'gifUrl': gif.bridgeHold,
          'audioLink': audio.BRIDGEHOLD,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.singleLegJackKnife,
          'circuit': 2,
          'index': 47,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SINGLELEGJACKKNIFETIP,
          'instructions': inst.singleLegJackKnife,
          'gifUrl': gif.singleLegJackKnife,
          'audioLink': audio.SINGLELEGJACKKNIFE,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingBentOverLongDumbbelsName,
          'circuit': 2,
          'index': 48,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGBENTOVERROWTIP,
          'instructions': inst.alternatingBentOverRowDumbberls,
          'gifUrl': gif.alternatingBentOverLongDumbbelsName,
          'audioLink': audio.ALTERNATINGBENTOVERROW,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.lateralRaise,
          'circuit': 2,
          'index': 49,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LATRAISETIP,
          'instructions': inst.lateralRaise,
          'gifUrl': gif.lateralRaise,
          'audioLink': audio.LATRAISETIP,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.inchWalk,
          'circuit': 3,
          'index': 50,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.INCHWALKTIP,
          'instructions': inst.inchWalk,
          'gifUrl': gif.inchWalk,
          'audioLink': audio.INCHWALK,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.tricepLift,
          'circuit': 3,
          'index': 51,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TRICEPLIFTTIP,
          'instructions': inst.tricepLift,
          'gifUrl': gif.tricepLift,
          'audioLink': audio.TRICEPLIFT,
        },
        {
          'level': 1,
          'week': 2,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfDeadBug,
          'circuit': 3,
          'index': 52,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFDEADBUGTIP,
          'instructions': inst.halfDeadBug,
          'gifUrl': gif.halfDeadBug,
          'audioLink': audio.HALFDEADBUG,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.mountainClimbers,
          'circuit': 1,
          'index': 53,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.MOUNTAINCLIMBERSTIP,
          'instructions': inst.mountainClimbers,
          'gifUrl': gif.mountainClimbers,
          'audioLink': audio.MOUNTAINCLIMBERS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squatAndLegLift,
          'circuit': 1,
          'index': 54,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATANDLEGLIFTTIP,
          'instructions': inst.squatAndLegLift,
          'gifUrl': gif.squatAndLegLift,
          'audioLink': audio.SQUATANDLEGLIFT,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.superMan,
          'circuit': 1,
          'index': 55,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUPERMANTIP,
          'instructions': inst.superMan,
          'gifUrl': gif.superMan,
          'audioLink': audio.SUPERMAN,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.crossToeTouches,
          'circuit': 2,
          'index': 56,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.CROSSTOETOUCHTIP,
          'instructions': inst.crossToeTouches,
          'gifUrl': gif.crossToeTouches,
          'audioLink': audio.CROSSTOETOUCHES,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gluteBridgesWieght,
          'circuit': 2,
          'index': 57,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GLUTEBRIDGETIP,
          'instructions': inst.gluteBridgesWieght,
          'gifUrl': gif.gluteBridgesWieght,
          'audioLink': audio.GLUTEBRIDGES,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bridgeHoldKicks,
          'circuit': 2,
          'index': 58,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BRIDGEKICKSTIP,
          'instructions': inst.bridgeHoldKicks,
          'gifUrl': gif.bridgeHoldKicks,
          'audioLink': audio.BRIDGEKICKS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingReverseLung,
          'circuit': 3,
          'index': 59,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGREVERSELUNGES,
          'instructions': inst.alternatingReverseLung,
          'gifUrl': gif.alternatingReverseLung,
          'audioLink': audio.ALTERNATINGREVERSELUNGES,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.highKnees,
          'circuit': 3,
          'index': 60,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HIGHKNEESTIP,
          'instructions': inst.highKnees,
          'gifUrl': gif.highKnees,
          'audioLink': audio.HIGHKNEES,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfSidePlankWithHipDip,
          'circuit': 3,
          'index': 61,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFSIDEPLANKHIPLIFTTIP,
          'instructions': inst.halfSidePlankWithHipDip,
          'gifUrl': gif.halfSidePlankWithHipDip,
          'audioLink': audio.HALFSIDEPLANKWITHHIPDIP,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.kneePullDowns,
          'circuit': 1,
          'index': 62,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.KNEEPULLDOWNSTIP,
          'instructions': inst.kneePullDowns,
          'gifUrl': gif.kneePullDowns,
          'audioLink': audio.KNEEPULLDOWNS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.narrowSquate,
          'circuit': 1,
          'index': 63,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.NARROWSQUATTIP,
          'instructions': inst.narrowSquate,
          'gifUrl': gif.narrowSquate,
          'audioLink': audio.NARROWSQUATS
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.sideStraightLegRaise,
          'circuit': 1,
          'index': 64,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SIDESTRAIGHTLEGRAISESTIP,
          'instructions': inst.sideStraightLegRaise,
          'gifUrl': gif.sideStraightLegRaise,
          'audioLink': audio.SIDESTRAIGHTLEGRAISE,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.shuttleRun,
          'circuit': 2,
          'index': 65,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SHUTTLERUNTIP,
          'instructions': inst.shuttleRun,
          'gifUrl': gif.shuttleRun,
          'audioLink': audio.SHUTTLERUNS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.calfRaise,
          'circuit': 2,
          'index': 66,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': 'beep.mp3',
          'instructions': inst.calfRaise,
          'gifUrl': gif.calfRaise,
          'audioLink': 'beep.mp3',
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingReverseLungAndTwist,
          'circuit': 2,
          'index': 67,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTLUNGEANDTWISTTIP,
          'instructions': inst.alternatingReverseLungAndTwist,
          'gifUrl': gif.alternatingReverseLungAndTwist,
          'audioLink': audio.ALTERNATINGLUNGEANDTWIST,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.lateralJumps,
          'circuit': 3,
          'index': 68,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LATERALJUMPSTIP,
          'instructions': inst.lateralJumps,
          'gifUrl': gif.lateralJumps,
          'audioLink': audio.LATERALJUMPS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.seatedAbuctions,
          'circuit': 3,
          'index': 69,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SEATEDHIPABDUCTIONSTIP,
          'instructions': inst.seatedAbuctions,
          'gifUrl': gif.seatedAbuctions,
          'audioLink': audio.SEATEDHIPABDUCTIONS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.sumoSquate,
          'circuit': 3,
          'index': 70,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUMOSQUATTIP,
          'instructions': inst.sumoSquate,
          'gifUrl': gif.sumoSquate,
          'audioLink': audio.SUMOSQUATS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bunnyHop,
          'circuit': 1,
          'index': 71,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BUNNYHOPTIP,
          'instructions': inst.bunnyHop,
          'gifUrl': gif.bunnyHop,
          'audioLink': audio.BUNNYHOP,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.uprightRow,
          'circuit': 1,
          'index': 72,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.UPRIGHTROWTIP,
          'instructions': inst.uprightRow,
          'gifUrl': gif.uprightRow,
          'audioLink': audio.UPRIGHTROW,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alterntatingLegRaise,
          'circuit': 1,
          'index': 73,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTLEGRAISETIP,
          'instructions': inst.alterntatingLegRaise,
          'gifUrl': gif.alterntatingLegRaise,
          'audioLink': audio.ALTERNATINGLEGRAISE,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.jabX5CrossX5,
          'circuit': 2,
          'index': 74,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.JABCROSSTIP,
          'instructions': inst.jabX5CrossX5,
          'gifUrl': gif.jabX5CrossX5,
          'audioLink': audio.JABCROSS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.halfBike,
          'circuit': 2,
          'index': 75,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFBIKETIP,
          'instructions': inst.halfBike,
          'gifUrl': gif.halfBike,
          'audioLink': audio.HALFBIKE,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingShoulderPressDumbbels,
          'circuit': 2,
          'index': 76,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGSHOULDERPRESS,
          'instructions': inst.alternatingShoulderPressDumbbels,
          'gifUrl': gif.alternatingShoulderPressDumbbels,
          'audioLink': audio.ALTERNATINGSHOULDERPRESS
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfBurpees,
          'circuit': 3,
          'index': 77,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFBURPEETIP,
          'instructions': inst.halfBurpees,
          'gifUrl': gif.halfBurpees,
          'audioLink': audio.HALFBURPEES,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingFloorChestPressName,
          'circuit': 3,
          'index': 78,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.CHESTPRESS,
          'instructions': inst.alternatingFloorChestPress,
          'gifUrl': gif.alternatingFloorChestPressName,
          'audioLink': audio.CHESTPRESS,
        },
        {
          'level': 1,
          'week': 3,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.singleArmTricepKickBackDubmmels,
          'circuit': 3,
          'index': 79,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SINGLEARMTRICEPKICKBACK,
          'instructions': inst.singleArmTricepKickBackDubmmels,
          'gifUrl': gif.singleArmTricepKickBackDubmmels,
          'audioLink': audio.SINGLEARMTRICEPKICKBACK,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.inclinePlankJacks,
          'circuit': 1,
          'index': 80,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.INCLINEPLANKJACKTIP,
          'instructions': inst.inclinePlankJacks,
          'gifUrl': gif.inclinePlankJacks,
          'audioLink': audio.INCLINEPLANKJACK,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squatAndLegLift,
          'circuit': 1,
          'index': 81,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATANDLEGLIFTTIP,
          'instructions': inst.squatAndLegLift,
          'gifUrl': gif.squatAndLegLift,
          'audioLink': audio.SQUATANDLEGLIFT,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingTricepKickBackDumbbels,
          'circuit': 1,
          'index': 82,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTTRIKICKBACKTIP,
          'instructions': inst.alternatingTricepKickBackDumbbels,
          'gifUrl': gif.alternatingTricepKickBackDumbbels,
          'audioLink': audio.ALTERNATINGTRICEPKICKBACK,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.sumoSquateDoublePulse,
          'circuit': 2,
          'index': 83,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUMOSQUATDOUBLEPULSETIP,
          'instructions': inst.sumoSquateDoublePulse,
          'gifUrl': gif.sumoSquateDoublePulse,
          'audioLink': audio.SUMOSQUATDOUBLEPULSE,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.ankleTaps,
          'circuit': 2,
          'index': 84,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ANKLETAPSTIP,
          'instructions': inst.ankleTaps,
          'gifUrl': gif.ankleTaps,
          'audioLink': audio.ANKLETAPS,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfWidePressUps,
          'circuit': 2,
          'index': 85,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFWIDEPRESSUPTIP,
          'instructions': inst.halfWidePressUps,
          'gifUrl': gif.halfWidePressUps,
          'audioLink': audio.HALFWIDEPRESSUPS,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingFrontRaiseName,
          'circuit': 3,
          'index': 86,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTLEGRAISETIP,
          'instructions': inst.alternatingFrontRaiseName,
          'gifUrl': gif.alternatingFrontRaiseName,
          'audioLink': audio.ALTFRONTRAISE,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.skipping,
          'circuit': 3,
          'index': 87,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SKIPPINGTIP,
          'instructions': inst.skipping,
          'gifUrl': gif.skipping,
          'audioLink': audio.SKIPPING,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.crunch,
          'circuit': 3,
          'index': 88,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.CRUNCHESTIP,
          'instructions': inst.crunch,
          'gifUrl': gif.crunch,
          'audioLink': audio.CRUNCHES,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.highKnees,
          'circuit': 1,
          'index': 89,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HIGHKNEESTIP,
          'instructions': inst.highKnees,
          'gifUrl': gif.highKnees,
          'audioLink': audio.HIGHKNEES
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gobletSquate,
          'circuit': 1,
          'index': 90,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GOBLETSQUAT,
          'instructions': inst.gobletSquate,
          'gifUrl': gif.gobletSquate,
          'audioLink': audio.GOBLETSQUAT,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gluteBridgesWieght,
          'circuit': 1,
          'index': 91,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GLUTEBRIDGETIP,
          'instructions': inst.gluteBridgesWieght,
          'gifUrl': gif.gluteBridgesWieght,
          'audioLink': audio.GLUTEBRIDGES,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfXJumps,
          'circuit': 2,
          'index': 92,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFXJUMPTIP,
          'instructions': inst.halfXJumps,
          'gifUrl': gif.halfXJumps,
          'audioLink': audio.HALFXJUMP,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.singleLegLunge,
          'circuit': 2,
          'index': 93,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SINGLELEGLUNGETIP,
          'instructions': inst.singleLegLunge,
          'gifUrl': gif.singleLegLunge,
          'audioLink': audio.SINGLELEGLUNGE,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.donkeyKick,
          'circuit': 2,
          'index': 94,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.DONKEYKICKTIP,
          'instructions': inst.donkeyKick,
          'gifUrl': gif.donkeyKick,
          'audioLink': audio.DONKEYKICKS,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.stepKneeDrive,
          'circuit': 3,
          'index': 95,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STEPKNEEDRIVETIP,
          'instructions': inst.stepKneeDrive,
          'gifUrl': gif.stepKneeDrive,
          'audioLink': audio.STEPKNEEDRIVE,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.innerThighLegLiftPulse,
          'circuit': 3,
          'index': 96,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.INNERTHIGHLIFTTIP,
          'instructions': inst.innerThighLegLiftPulse,
          'gifUrl': gif.innerThighLegLiftPulse,
          'audioLink': audio.INNERTHIGHLEGLIFT,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.standingSideKick,
          'circuit': 3,
          'index': 97,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STANDINGSIDEKICKTIP,
          'instructions': inst.standingSideKick,
          'gifUrl': gif.standingSideKick,
          'audioLink': audio.STANDINGSIDEKICK,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.crossMountainClimbers,
          'circuit': 1,
          'index': 98,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.CROSSMOUNTAINCLIMBERTIP,
          'instructions': inst.crossMountainClimbers,
          'gifUrl': gif.crossMountainClimbers,
          'audioLink': audio.CROSSMOUNTAINCLIMBERS,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bicepCurles,
          'circuit': 1,
          'index': 99,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BICEPCURLCOACHINGTIP,
          'instructions': inst.bicepCurles,
          'gifUrl': gif.bicepCurles,
          'audioLink': audio.BICEPCURLTIP,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.tricepDipsBench,
          'circuit': 1,
          'index': 100,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TRIDIPSBENCHTIP,
          'instructions': inst.tricepDipsBench,
          'gifUrl': gif.tricepDipsBench,
          'audioLink': audio.TRICEPDIPS,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingHalfClock,
          'circuit': 2,
          'index': 101,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGHALFCLOCK,
          'instructions': inst.alternatingHalfClock,
          'gifUrl': gif.alternatingHalfClock,
          'audioLink': audio.ALTERNATINGHALFCLOCK,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.halfSidePlankWithHipDip,
          'circuit': 2,
          'index': 102,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFSIDEPLANKWITHHIPDIP,
          'instructions': inst.halfSidePlankWithHipDip,
          'gifUrl': gif.halfSidePlankWithHipDip,
          'audioLink': audio.HALFSIDEPLANKWITHHIPDIP,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingSeatedRow,
          'circuit': 2,
          'index': 103,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SEATEDROWTIP,
          'instructions': inst.alternatingSeatedRow,
          'gifUrl': gif.alternatingSeatedRow,
          'audioLink': audio.ALTERNATINGSEATEDROW,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.explosiveStarJumps,
          'circuit': 3,
          'index': 104,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.EXPLOSIVESJUMPSTIP,
          'instructions': inst.explosiveStarJumps,
          'gifUrl': gif.explosiveStarJumps,
          'audioLink': audio.EXPLOSIVESTARJUMPS,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.superManRow,
          'circuit': 3,
          'index': 105,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUPERMANROWTIP,
          'instructions': inst.superManRow,
          'gifUrl': gif.superManRow,
          'audioLink': audio.SUPERMANROW,
        },
        {
          'level': 1,
          'week': 4,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfWidePressUps,
          'circuit': 3,
          'index': 106,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFWIDEPRESSUPTIP,
          'instructions': inst.halfWidePressUps,
          'gifUrl': gif.halfWidePressUps,
          'audioLink': audio.HALFWIDEPRESSUPS,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.inchWalkAndPressUp,
          'circuit': 1,
          'index': 107,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.INCHWALKANDHALFPRESSUPTIP,
          'instructions': inst.inchWalkAndPressUp,
          'gifUrl': gif.inchWalkAndPressUp,
          'audioLink': audio.INCHWALKANDHALFPRESSUP,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.popSquats,
          'circuit': 1,
          'index': 108,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.POPSQUATTIP,
          'instructions': inst.popSquats,
          'gifUrl': gif.popSquats,
          'audioLink': audio.POPSQUATS,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingReverseLungAndTwistWithWeight,
          'circuit': 1,
          'index': 109,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGLUNGEANDTWIST,
          'instructions': inst.alternatingReverseLungAndTwistWithWeight,
          'gifUrl': gif.alternatingReverseLungAndTwistWithWeight,
          'audioLink': audio.ALTERNATINGLUNGEANDTWIST,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gluteBridgeKnee,
          'circuit': 2,
          'index': 110,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GLUTEBRIDGEKNEETIP,
          'instructions': inst.gluteBridgeKnee,
          'gifUrl': gif.gluteBridgeKnee,
          'audioLink': audio.GLUTEBRIDGEANDKNEE,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bunnyHop,
          'circuit': 2,
          'index': 111,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BUNNYHOPTIP,
          'instructions': inst.bunnyHop,
          'gifUrl': gif.bunnyHop,
          'audioLink': audio.BUNNYHOP,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bentLegRaiseAndHipLift,
          'circuit': 2,
          'index': 112,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BENTLEGRAISEANDHIPLIFT,
          'instructions': inst.bentLegRaiseAndHipLift,
          'gifUrl': gif.bentLegRaiseAndHipLift,
          'audioLink': audio.BENTLEGRAISEANDHIPLIFT,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.tricepDipsBench,
          'circuit': 3,
          'index': 113,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TRIDIPSBENCHTIP,
          'instructions': inst.tricepDipsBench,
          'gifUrl': gif.tricepDipsBench,
          'audioLink': audio.TRICEPDIPS,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.fastObliqueTwist,
          'circuit': 3,
          'index': 114,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.FASTOBLIQUETWISTTIP,
          'instructions': inst.fastObliqueTwist,
          'gifUrl': gif.fastObliqueTwist,
          'audioLink': 'beep.mp3',
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.jabX5CrossX5,
          'circuit': 3,
          'index': 115,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.JABCROSSTIP,
          'instructions': inst.jabX5CrossX5,
          'gifUrl': gif.jabX5CrossX5,
          'audioLink': audio.JABCROSS,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.skipping,
          'circuit': 1,
          'index': 116,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SKIPPINGTIP,
          'instructions': inst.skipping,
          'gifUrl': gif.skipping,
          'audioLink': audio.SKIPPING,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.lateralKneeDrive,
          'circuit': 1,
          'index': 117,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LATERALKNEEDRIVETIP,
          'instructions': inst.lateralKneeDrive,
          'gifUrl': gif.lateralKneeDrive,
          'audioLink': audio.LATERALKNEEDRIVE,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.frogGluteBridges,
          'circuit': 1,
          'index': 118,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.FROGGLUTEBRIDGETIP,
          'instructions': inst.frogGluteBridges,
          'gifUrl': gif.frogGluteBridges,
          'audioLink': audio.FROGGLUTEBRIDGES,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squatAndTouch,
          'circuit': 2,
          'index': 120,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATANDTOUCHTIP,
          'instructions': inst.squatAndTouch,
          'gifUrl': gif.squatAndTouch,
          'audioLink': audio.SQUATANDTOUCH,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.standingGluteKickback,
          'circuit': 2,
          'index': 121,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.STANDINGGLUTEKICKBACKTIP,
          'instructions': inst.standingGluteKickback,
          'gifUrl': gif.standingGluteKickback,
          'audioLink': audio.STANDINGGLUTEKICKBACK,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingReverseLungDumbbels,
          'circuit': 2,
          'index': 122,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTERNATINGREVERSELUNGES,
          'instructions': inst.alternatingReverseLungDumbbels,
          'gifUrl': gif.alternatingReverseLungDumbbels,
          'audioLink': audio.ALTERNATINGREVERSELUNGES,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfBurpees,
          'circuit': 3,
          'index': 123,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFBURPEETIP,
          'instructions': inst.halfBurpees,
          'gifUrl': gif.halfBurpees,
          'audioLink': audio.HALFBURPEES
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.fireHydrantLoopResistanceBand,
          'circuit': 3,
          'index': 124,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.FIREHYDRANTTIPS,
          'instructions': inst.fireHydrantLoopResistanceBand,
          'gifUrl': gif.fireHydrantLoopResistanceBand,
          'audioLink': audio.FIREHYDRANT,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.sumoSquateWeight,
          'circuit': 3,
          'index': 125,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUMOSQUATTIP,
          'instructions': inst.sumoSquateWeight,
          'gifUrl': gif.sumoSquateWeight,
          'audioLink': audio.SUMOSQUATS,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.armCirclesWithWeight,
          'circuit': 1,
          'index': 126,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ARMCIRCLESTIP,
          'instructions': inst.armCirclesWithWeight,
          'gifUrl': gif.armCirclesWithWeight,
          'audioLink': audio.ARMCIRCLES,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.legsUpCrunch,
          'circuit': 1,
          'index': 127,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LEGSUPCRUNCHTIP,
          'instructions': inst.legsUpCrunch,
          'gifUrl': gif.legsUpCrunch,
          'audioLink': audio.LEGSUPCRUNCHES,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bridgeHoldKicks,
          'circuit': 1,
          'index': 128,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BRIDGEKICKSKEEPTIP,
          'instructions': inst.bridgeHoldKicks,
          'gifUrl': gif.bridgeHoldKicks,
          'audioLink': audio.BRIDGEKICKSTIP,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bentLegJackknife,
          'circuit': 2,
          'index': 129,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BENTLEGJACKKNIFETIP,
          'instructions': inst.bentLegJackknife,
          'gifUrl': gif.bentLegJackknife,
          'audioLink': audio.BENTLEGJACKKNIFE,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bentOverRowDubmmels,
          'circuit': 2,
          'index': 130,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BENTOVERROWTIP,
          'instructions': inst.bentOverRowDubmmels,
          'gifUrl': gif.bentOverRowDubmmels,
          'audioLink': audio.BENTOVERROW,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingFrontRaiseName,
          'circuit': 2,
          'index': 131,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTFRONTRAISE,
          'instructions': inst.alternatingFrontRaiseName,
          'gifUrl': gif.alternatingFrontRaiseName,
          'audioLink': audio.ALTFRONTRAISE,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.plank,
          'circuit': 3,
          'index': 132,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.PLANKTIP,
          'instructions': inst.plank,
          'gifUrl': gif.plank,
          'audioLink': audio.PLANK,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.tricepExtension,
          'circuit': 3,
          'index': 133,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.TRICEPDIPTIP,
          'instructions': inst.tricepExtension,
          'gifUrl': gif.tricepExtension,
          'audioLink': audio.TRICEPDIPS,
        },
        {
          'level': 1,
          'week': 5,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfDeadBug,
          'circuit': 3,
          'index': 134,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFDEADBUGTIP,
          'instructions': inst.halfDeadBug,
          'gifUrl': gif.halfDeadBug,
          'audioLink': audio.HALFDEADBUG,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.explosiveStarJumps,
          'circuit': 1,
          'index': 135,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.EXPLOSIVESJUMPSTIP,
          'instructions': inst.explosiveStarJumps,
          'gifUrl': gif.explosiveStarJumps,
          'audioLink': audio.EXPLOSIVESTARJUMPS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.heelTouches,
          'circuit': 1,
          'index': 136,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HEELTOUCHESTIP,
          'instructions': inst.heelTouches,
          'gifUrl': gif.heelTouches,
          'audioLink': audio.HEELTOUCHES,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.bentOverRowDubmmels,
          'circuit': 1,
          'index': 137,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BENTOVERROWTIP,
          'instructions': inst.bentOverRowDubmmels,
          'gifUrl': gif.bentOverRowDubmmels,
          'audioLink': audio.BENTOVERROW,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gobletSquate,
          'circuit': 2,
          'index': 138,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GOBLETSQUAT,
          'instructions': inst.gobletSquate,
          'gifUrl': gif.gobletSquate,
          'audioLink': audio.GOBLETSQUAT
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.lateralRaise,
          'circuit': 2,
          'index': 139,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LATERALRAISE,
          'instructions': inst.lateralRaise,
          'gifUrl': gif.lateralRaise,
          'audioLink': audio.LATERALRAISE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.assitedCrunchWhammy,
          'circuit': 2,
          'index': 140,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ASSISTEDCRUNCHWHAMMYTIP,
          'instructions': inst.assitedCrunchWhammy,
          'gifUrl': gif.assitedCrunchWhammy,
          'audioLink': audio.ASSISTEDCRUNCHWHAMMY,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.superManRow,
          'circuit': 3,
          'index': 141,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUPERMANROWTIP,
          'instructions': inst.superManRow,
          'gifUrl': gif.superManRow,
          'audioLink': audio.SUPERMANROW,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.burpess,
          'circuit': 3,
          'index': 142,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BURPEESTIP,
          'instructions': inst.burpess,
          'gifUrl': gif.burpess,
          'audioLink': audio.BURPEES,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 1,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.elevatedGluteBridgesBench,
          'circuit': 3,
          'index': 143,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ELEVATEDGLUTEBRIDGETIP,
          'instructions': inst.elevatedGluteBridgesBench,
          'gifUrl': gif.elevatedGluteBridgesBench,
          'audioLink': audio.ELEVATEDGLUTEBRIDGE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.fastObliqueTwist,
          'circuit': 1,
          'index': 144,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.FASTSINGLELEGOBLIQUETWISTTIP,
          'instructions': inst.fastObliqueTwist,
          'gifUrl': gif.fastObliqueTwist,
          'audioLink': audio.FASTSINGLELEGOBLIQUETWISTS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.squatAndCalfRaise,
          'circuit': 1,
          'index': 145,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SQUATCALFRAISETIP,
          'instructions': inst.squatAndCalfRaise,
          'gifUrl': gif.squatAndCalfRaise,
          'audioLink': audio.SQUATANDCALFRAISE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.sideStraightLegRaise,
          'circuit': 1,
          'index': 146,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SIDESTRAIGHTLEGRAISESTIP,
          'instructions': inst.sideStraightLegRaise,
          'gifUrl': gif.sideStraightLegRaise,
          'audioLink': audio.SIDESTRAIGHTLEGRAISE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.broadJumps,
          'circuit': 2,
          'index': 147,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BROADJUMPSTIP,
          'instructions': inst.broadJumps,
          'gifUrl': gif.broadJumps,
          'audioLink': audio.BROADJUMPS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gluteKickBackLoopBand,
          'circuit': 2,
          'index': 148,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GLUTEKICKBACKTIP,
          'instructions': inst.gluteKickBackLoopBand,
          'gifUrl': gif.gluteKickBackLoopBand,
          'audioLink': audio.GLUTEKICKBACK,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.singleLegLunge,
          'circuit': 2,
          'index': 149,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SINGLELEGLUNGETIP,
          'instructions': inst.singleLegLunge,
          'gifUrl': gif.singleLegLunge,
          'audioLink': audio.SINGLELEGLUNGE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.lateralJumps,
          'circuit': 3,
          'index': 150,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.LATERALJUMPSTIP,
          'instructions': inst.lateralJumps,
          'gifUrl': gif.lateralJumps,
          'audioLink': audio.LATERALJUMPS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.gluteBrigesAbudctions,
          'circuit': 3,
          'index': 151,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.GLUTEBRIDGEABDUCTIONSTIP,
          'instructions': inst.gluteBrigesAbudctions,
          'gifUrl': gif.gluteBrigesAbudctions,
          'audioLink': audio.GLUTEBRIDGEABDUCTIONS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 2,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.sumoSquateDoublePulseWeight,
          'circuit': 3,
          'index': 152,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SUMOSQUATDOUBLEPULSETIP,
          'instructions': inst.sumoSquateDoublePulseWeight,
          'gifUrl': gif.sumoSquateDoublePulseWeight,
          'audioLink': audio.SUMOSQUATDOUBLEPULSE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.highKnees,
          'circuit': 1,
          'index': 153,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HIGHKNEESTIP,
          'instructions': inst.highKnees,
          'gifUrl': gif.highKnees,
          'audioLink': audio.HIGHKNEES,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfPlankAlternatingRow,
          'circuit': 1,
          'index': 154,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFPLANKROWTIP,
          'instructions': inst.halfPlankAlternatingRow,
          'gifUrl': gif.halfPlankAlternatingRow,
          'audioLink': audio.ALTERNATINGHALFPLANKROW,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alterntatingLegRaise,
          'circuit': 1,
          'index': 155,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTLEGRAISETIP,
          'instructions': inst.alterntatingLegRaise,
          'gifUrl': gif.alterntatingLegRaise,
          'audioLink': audio.ALTERNATINGLEGRAISE,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.jabX5CrossX5,
          'circuit': 2,
          'index': 156,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.JABCROSSTIP,
          'instructions': inst.jabX5CrossX5,
          'gifUrl': gif.jabX5CrossX5,
          'audioLink': audio.JABCROSS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': true,
          'sideSwitchTime': 20,
          'exerciseName': names.singleLegAbBikes,
          'circuit': 2,
          'index': 157,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SINGLELEGBIKETIP,
          'instructions': inst.singleLegAbBikes,
          'gifUrl': gif.singleLegAbBikes,
          'audioLink': audio.SINGLELEGBICYCLES,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.shoulderPress,
          'circuit': 2,
          'index': 158,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.SHOULDERPRESSTIP,
          'instructions': inst.shoulderPress,
          'gifUrl': gif.shoulderPress,
          'audioLink': audio.SHOULDERPRESS,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.burpess,
          'circuit': 3,
          'index': 159,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.BURPEESTIP,
          'instructions': inst.burpess,
          'gifUrl': gif.burpess,
          'audioLink': audio.BURPEES,
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.halfWidePressUps,
          'circuit': 3,
          'index': 160,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.HALFWIDEPRESSUPTIP,
          'instructions': inst.halfWidePressUps,
          'gifUrl': gif.halfWidePressUps,
          'audioLink': audio.HALFWIDEPRESSUPS
        },
        {
          'level': 1,
          'week': 6,
          'place': 2,
          'workoutType': 3,
          'sideSwitch': false,
          'sideSwitchTime': 20,
          'exerciseName': names.alternatingTricepKickbackLongResistenceBand,
          'circuit': 3,
          'index': 161,
          // 03414687643
          'exerciseTime': 40,
          'restTime': 15,
          'audioTip': audioT.ALTTRIKICKBACKTIP,
          'instructions': inst.alternatingTricepKickbackLongResistenceBand,
          'gifUrl': gif.alternatingTricepKickbackLongResistenceBand,
          'audioLink': audio.ALTERNATINGTRICEPKICKBACK,
        },
      ]
    },
    {
      'activations': [
        {
          'exerciseName': 'Toe Taps',
          'level': 1,
          'week': 1,
          'place': 2,
          'repeat': 40,
          'workoutType': 2,
          'activationImageUrl':
              'https://www.pngmart.com/files/7/Kettlebell-PNG-Free-Download.png',
        },
        {
          'exerciseName': 'Donkey Kicks (Left)',
          'level': 1,
          'week': 1,
          'place': 2,
          'repeat': 10,
          'workoutType': 2,
          'activationImageUrl':
              'https://www.pngmart.com/files/7/Kettlebell-PNG-Free-Download.png',
        },
        {
          'exerciseName': 'Donkey Kicks (Right)',
          'level': 1,
          'week': 1,
          'place': 2,
          'repeat': 10,
          'workoutType': 2,
          'activationImageUrl':
              'https://www.pngmart.com/files/7/Kettlebell-PNG-Free-Download.png',
        },
        {
          'exerciseName': 'Half Starjumps',
          'level': 1,
          'week': 1,
          'place': 2,
          'repeat': 24,
          'workoutType': 3,
          'activationImageUrl':
              'https://www.pngmart.com/files/7/Kettlebell-PNG-Free-Download.png',
        },
        {
          'exerciseName': 'Shoulder Rotations',
          'level': 1,
          'week': 1,
          'place': 2,
          'repeat': 10,
          'workoutType': 3,
          'activationImageUrl':
              'https://www.pngmart.com/files/7/Kettlebell-PNG-Free-Download.png',
        },
      ]
    },
  ];
}
